/*eslint-env node, mocha*/
/**
 * Generated by PluginGenerator 2.20.5 from webgme on Mon Jul 10 2023 16:45:34 GMT-0500 (Central Daylight Time).
 */

describe("SetPdpReadToken", function () {
  const assert = require("assert");
  const withTokens =
    require("../../../src/routers/Search/build/adapters/PDP/tokens")
      .default;

  var testFixture = require("../../globals"),
    gmeConfig = testFixture.getGmeConfig(),
    expect = testFixture.expect,
    logger = testFixture.logger.fork("SetPdpReadToken"),
    PluginCliManager = testFixture.WebGME.PluginCliManager,
    projectName = "testProject",
    pluginName = "SetPdpReadToken",
    project,
    gmeAuth,
    storage,
    commitHash;

  before(function (done) {
    testFixture.clearDBAndGetGMEAuth(gmeConfig, projectName)
      .then(function (gmeAuth_) {
        gmeAuth = gmeAuth_;
        // This uses in memory storage. Use testFixture.getMongoStorage to persist test to database.
        storage = testFixture.getMemoryStorage(logger, gmeConfig, gmeAuth);
        return storage.openDatabase();
      })
      .then(function () {
        var importParam = {
          projectSeed: testFixture.path.join(
            testFixture.SEED_DIR,
            "EmptyProject.webgmex",
          ),
          projectName: projectName,
          branchName: "master",
          logger: logger,
          gmeConfig: gmeConfig,
        };

        return testFixture.importProject(storage, importParam);
      })
      .then(function (importResult) {
        project = importResult.project;
        commitHash = importResult.commitHash;
        return project.createBranch("test", commitHash);
      })
      .nodeify(done);
  });

  after(function (done) {
    storage.closeDatabase()
      .then(function () {
        return gmeAuth.unload();
      })
      .nodeify(done);
  });

  it("should run plugin and update the branch", function (done) {
    var manager = new PluginCliManager(null, logger, gmeConfig),
      pluginConfig = {
        token: "someSecretToken",
      },
      context = {
        project: project,
        commitHash: commitHash,
        branchName: "test",
        activeNode: "/1",
      };

    manager.executePlugin(
      pluginName,
      pluginConfig,
      context,
      async function (err, pluginResult) {
        try {
          expect(err).to.equal(null);
          expect(typeof pluginResult).to.equal("object");
          expect(pluginResult.success).to.equal(true);
        } catch (e) {
          done(e);
          return;
        }
        // check that the token has been saved
        const token = await withTokens(
          gmeConfig,
          (tokens) => tokens.get(project.projectId),
        );
        assert.equal(pluginConfig.token, token);

        // No edits to the project
        project.getBranchHash("test")
          .then(function (branchHash) {
            expect(branchHash).to.equal(commitHash);
          })
          .nodeify(done);
      },
    );
  });
});
