// DO NOT EDIT THIS FILE
// This file is automatically generated from the webgme-setup-tool.
'use strict';


var config = require('webgme/config/config.default'),
    validateConfig = require('webgme/config/validator');

// The paths can be loaded from the webgme-setup.json
config.plugin.basePaths.push(__dirname + '/../build/plugins');
config.plugin.basePaths.push(__dirname + '/../node_modules/webgme-json-importer/src/plugins');
config.seedProjects.basePaths.push(__dirname + '/../seeds/taxonomy');
config.seedProjects.basePaths.push(__dirname + '/../seeds/TaxonomyProject');
config.seedProjects.basePaths.push(__dirname + '/../seeds/profile');
config.seedProjects.basePaths.push(__dirname + '/../seeds/test');



config.rest.components['Search'] = {
  src: __dirname + '/../build/routers/Search/Search.js',
  mount: 'routers/Search',
  options: {}
};
config.rest.components['TagFormat'] = {
  src: __dirname + '/../build/routers/TagFormat/TagFormat.js',
  mount: 'routers/TagFormat',
  options: {}
};
config.rest.components['TagCreator'] = {
  src: __dirname + '/../build/routers/TagCreator/TagCreator.js',
  mount: 'routers/TagCreator',
  options: {}
};
config.rest.components['JSONSchema'] = {
  src: __dirname + '/../build/routers/JSONSchema/JSONSchema.js',
  mount: 'routers/JSONSchema',
  options: {}
};
config.rest.components['Dashboard'] = {
  src: __dirname + '/../build/routers/Dashboard/Dashboard.js',
  mount: 'routers/Dashboard',
  options: {}
};
config.rest.components['Profiles'] = {
  src: __dirname + '/../build/routers/Profiles/Profiles.js',
  mount: 'routers/Profiles',
  options: {}
};
config.rest.components['JSONSchemav1'] = {
  src: __dirname + '/../build/routers/JSONSchemav1/JSONSchemav1.js',
  mount: 'routers/JSONSchemav1',
  options: {}
};
config.rest.components['TagCreatorv1'] = {
  src: __dirname + '/../build/routers/TagCreatorv1/TagCreatorv1.js',
  mount: 'routers/TagCreatorv1',
  options: {}
};
config.rest.components['Insights'] = {
  src: __dirname + '/../build/routers/Insights/Insights.js',
  mount: 'routers/Insights',
  options: {}
};

// Add requirejs paths
config.requirejsPaths = {
  'SetStateFromJSON': 'node_modules/webgme-json-importer/src/plugins/SetStateFromJSON',
  'panels': './src/visualizers/panels',
  'widgets': './src/visualizers/widgets',
  'webgme-json-importer': './node_modules/webgme-json-importer/src/common',
  'webgme-taxonomy': './src/common'
};


config.mongo.uri = 'mongodb://127.0.0.1:27017/webgme_taxonomy';
validateConfig(config);
module.exports = config;
