name: "sub-action"

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        type: string
      runs-on:
        type: string
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true

jobs:
  sub_action:
    name: "Sub Action name"
    runs-on: "ubuntu-latest"

    steps:
      - name: "sub action details"
        run: |
          echo "::group::Event API attributes"
          echo "subaction ${{github.actor}}"
          echo "::endgroup::"
