/*globals define*/
/*eslint-env node, browser*/

/**
 * Generated by PluginGenerator 2.20.5 from webgme on Wed Nov 30 2022 13:39:26 GMT-0600 (Central Standard Time).
 * A plugin that inherits from the PluginBase. To see source code documentation about available
 * properties and methods visit %host%/docs/source/PluginBase.html.
 */

define(["text!./metadata.json", "plugin/PluginBase"], function (
  pluginMetadata,
  PluginBase
) {
  "use strict";

  pluginMetadata = JSON.parse(pluginMetadata);

  /**
   * Initializes a new instance of OpenContentTypeDashboard.
   * @class
   * @augments {PluginBase}
   * @classdesc This class represents the plugin OpenContentTypeDashboard.
   * @constructor
   */
  class OpenContentTypeDashboard extends PluginBase {
    constructor() {
      super();
      this.pluginMetadata = pluginMetadata;
    }

    async main() {
      // TODO: get project ID
      // TODO: get tags
      // TODO: get branch names
      // TODO: get commit hash
      const baseUrl = window.location.href.replace(/\?.*$/, "");
      console.log("project id:", this.project.projectId);
      const versionString = await this.getVersionString();
      const url =
        baseUrl +
        "routers/Dashboard/" +
        encodeURIComponent(this.project.projectId) +
        "/" +
        versionString +
        "/static/index.html";
      openUrl(url);
      this.result.setSuccess(true);
    }

    async getVersionString() {
      return Object.entries(await this.getVersion())
        .map(([name, value]) => name + "/" + encodeURIComponent(value))
        .pop();
    }

    async getVersion() {
      const versionInfo = {};
      const tags = await this.project.getTags();
      const currentTag = Object.entries(tags).find(
        ([tag, commit]) => commit === this.commitHash
      );

      if (currentTag) {
        versionInfo.tag = currentTag[0];
      } else if (this.branchName) {
        versionInfo.branch = this.branchName;
      } else {
        versionInfo.commit = this.commitHash;
      }

      return versionInfo;
    }
  }

  function openUrl(url) {
    const anchor = document.createElement("a");
    anchor.setAttribute("href", url);
    anchor.setAttribute("target", "_blank");
    anchor.click();
  }

  OpenContentTypeDashboard.metadata = pluginMetadata;

  return OpenContentTypeDashboard;
});
