// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Variant } from "./Variant";
import type { VariantId } from "./VariantId";

export interface EnumContent { value?: VariantId, variants: Array<Variant>, }