// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BooleanContent } from "./BooleanContent";
import type { FloatContent } from "./FloatContent";
import type { IntegerContent } from "./IntegerContent";
import type { TextContent } from "./TextContent";
import type { UriContent } from "./UriContent";

export type FieldContent =
  | { "Text": TextContent }
  | { "Integer": IntegerContent }
  | { "Float": FloatContent }
  | { "Boolean": BooleanContent }
  | { "Uri": UriContent };
