// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldContent } from "./FieldContent";
import type { FieldId } from "./FieldId";

export interface Field {
  id: FieldId;
  description: string;
  required: boolean;
  content: FieldContent;
}
