// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VocabularyData } from "./VocabularyData";
import type { VocabularyName } from "./VocabularyName";

export interface Taxonomy {
  vocabularies: Record<VocabularyName, VocabularyData>;
}
