// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Field } from "./Field";
import type { FieldName } from "./FieldName";
import type { ReleaseState } from "./ReleaseState";
import type { SelectionConstraint } from "./SelectionConstraint";
import type { TermId } from "./TermId";

export interface Term { id: TermId, selection: SelectionConstraint, description?: string, releaseState?: ReleaseState, readOnly: boolean, fields: Record<FieldName, Field>, }