name: "CI"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    timeout-minutes: 60
    name: "Test"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Branch"
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: "Start MongoDB"
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: "5.0"

      - name: "Install Dependencies"
        run: npm i
        env:
          NODE_ENV: test

      - name: "Unit Tests"
        run: npm test

      # Setup integration tests
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Start server
        run: npm start &
      - name: Wait for server to accept connections
        id: waitForCloud
        uses: ifaxity/wait-on-action@v1
        with:
          resource: http-get://localhost:8080
          timeout: 30000 # 30 seconds

      - name: Integration Tests
        run: npm run setup-e2e && npm run test-e2e

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
