name: "Integrated Testing"

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        type: string
      runs-on:
        type: string
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    if: ${{ github.actor == 'dax-westerman'}}
    steps:
      - uses: ./.github/workflows/integration-tests/sub-action.yml
